### ISSUE TITLE
How to render zero-shot transfer policy?

### ISSUE THREAD

**Issue by chongyi-zheng** [jhejna/hierarchical_morphology_transfer#4]
I want to render a zero-shot high-level policy after training. In other words, I have trained PointMaze_High and AntMaze_Low policies and want to combine them.

The `test_model.py` renders only one policy at a time, and the `test_hrl_model.py` requires the high-level and the low-level environments to match as well.

**Comment by jhejna** [comment]
Once you have trained a high level policy, it will additionally store the low level policy. You just need to run the test script on the high level policy. One note is that you shouldn't train the low level for Ant on AntMaze_Low, as this will train the Ant with the maze walls in place. Rather, it's best to train the ant low policy on just the Ant_Low environment.

**Comment by chongyi-zheng** [comment]
@jhejna Thanks for you reply! Okay, all I need to do is to train a PointMaze_High and Ant_Low, then combine them with `composition_test.py` script.
